# Lab 2: DataFrame Operations
| File | Rows | Columns | Description |
|------|------|---------|-------------|
| `bank_clients_A.csv` | 15 | 9 | Client demographics + balance |
| `bank_clients_B.csv` | 12 | 8 | Campaign contact info |

In [ ]:
import pandas as pd

df_A = pd.read_csv('bank_clients_A.csv')
df_B = pd.read_csv('bank_clients_B.csv')

print('Dataset A shape:', df_A.shape)
print('Dataset B shape:', df_B.shape)

print('\n--- Dataset A ---')
display(df_A)

print('\n--- Dataset B ---')
display(df_B)

## Concatenation

In [2]:
df_concat = pd.concat([df_A, df_B], axis=0, ignore_index=True)

print('Shape after concatenation:', df_concat.shape)
print(f'  = {df_A.shape[0]} rows (A) + {df_B.shape[0]} rows (B)\n')
display(df_concat)

Shape after concatenation: (27, 12)
  = 15 rows (A) + 12 rows (B)

,client_id,age,job,marital,education,balance,housing,loan,subscribed,campaign_calls,contact,outcome
0,1,34,admin,single,university.degree,1500.0,yes,no,yes,NaN,NaN,NaN
1,2,45,blue-collar,married,high.school,800.0,yes,yes,no,NaN,NaN,NaN
2,3,29,technician,single,university.degree,2100.0,no,no,yes,NaN,NaN,NaN
3,4,52,services,divorced,basic.9y,300.0,yes,no,no,NaN,NaN,NaN
4,5,41,management,married,university.degree,5200.0,no,no,yes,NaN,NaN,NaN
5,6,38,technician,single,professional.course,1800.0,yes,no,yes,NaN,NaN,NaN
6,7,60,retired,married,basic.4y,9800.0,no,no,yes,NaN,NaN,NaN
7,8,27,student,single,university.degree,100.0,no,no,no,NaN,NaN,NaN
8,9,48,entrepreneur,divorced,high.school,640.0,yes,yes,no,NaN,NaN,NaN
9,10,35,admin,married,university.degree,2300.0,yes,no,yes,NaN,NaN,NaN
10,11,55,housemaid,married,basic.4y,450.0,yes,no,no,NaN,NaN,NaN
11,12,43,self-employed,single,professional.course,3100.0,no,no,no,NaN,NaN,NaN
12,13,31,unemployed,single,high.school,200.0,no,yes,no,NaN,NaN,NaN
13,14,50,management,married,university.degree,7600.0,no,no,yes,NaN,NaN,NaN
14,15,26,student,single,university.degree,80.0,no,no,no,NaN,NaN,NaN
15,1,34,admin,single,university.degree,NaN,NaN,NaN,NaN,2.0,cellular,yes
16,3,29,technician,single,university.degree,NaN,NaN,NaN,NaN,1.0,cellular,yes
17,5,41,management,married,university.degree,NaN,NaN,NaN,NaN,3.0,telephone,yes
18,7,60,retired,married,basic.4y,NaN,NaN,NaN,NaN,1.0,cellular,yes
19,9,48,entrepreneur,divorced,high.school,NaN,NaN,NaN,NaN,4.0,cellular,no
20,11,55,housemaid,married,basic.4y,NaN,NaN,NaN,NaN,2.0,telephone,no
21,13,31,unemployed,single,high.school,NaN,NaN,NaN,NaN,5.0,cellular,no
22,16,44,admin,divorced,university.degree,NaN,NaN,NaN,NaN,2.0,cellular,yes
23,17,33,technician,married,professional.course,NaN,NaN,NaN,NaN,1.0,cellular,yes
24,18,58,retired,married,basic.9y,NaN,NaN,NaN,NaN,1.0,cellular,yes
25,19,22,student,single,university.degree,NaN,NaN,NaN,NaN,3.0,cellular,no
26,20,47,management,married,university.degree,NaN,NaN,NaN,NaN,2.0,telephone,yes

## Merging on client_id
- **Dataset A** → demographics & balance
- **Dataset B** → campaign contact info

We join on the unique key client_id to enrich each client's record.

### Inner Merge
Returns only clients whose `client_id` exists in both A and B.

In [3]:
df_inner = pd.merge(df_A, df_B, on='client_id', how='inner')

print('Inner merge shape:', df_inner.shape)
print('client_ids kept:', df_inner['client_id'].tolist())
display(df_inner)

Inner merge shape: (7, 16)
client_ids kept: [1, 3, 5, 7, 9, 11, 13]

,client_id,age_x,job_x,marital_x,education_x,balance,housing,loan,subscribed,age_y,job_y,marital_y,education_y,campaign_calls,contact,outcome
0,1,34,admin,single,university.degree,1500,yes,no,yes,34,admin,single,university.degree,2,cellular,yes
1,3,29,technician,single,university.degree,2100,no,no,yes,29,technician,single,university.degree,1,cellular,yes
2,5,41,management,married,university.degree,5200,no,no,yes,41,management,married,university.degree,3,telephone,yes
3,7,60,retired,married,basic.4y,9800,no,no,yes,60,retired,married,basic.4y,1,cellular,yes
4,9,48,entrepreneur,divorced,high.school,640,yes,yes,no,48,entrepreneur,divorced,high.school,4,cellular,no
5,11,55,housemaid,married,basic.4y,450,yes,no,no,55,housemaid,married,basic.4y,2,telephone,no
6,13,31,unemployed,single,high.school,200,no,yes,no,31,unemployed,single,high.school,5,cellular,no

### Left Merge
Returns all rows from A; fills NaN for clients not found in B.

In [4]:
df_left = pd.merge(df_A, df_B, on='client_id', how='left')

print('Left merge shape:', df_left.shape)
print('Clients only in A (NaN in campaign columns):', df_left[df_left['outcome'].isna()]['client_id'].tolist())
display(df_left)

Left merge shape: (15, 16)
Clients only in A (NaN in campaign columns): [2, 4, 6, 8, 10, 12, 14, 15]

,client_id,age_x,job_x,marital_x,education_x,balance,housing,loan,subscribed,age_y,job_y,marital_y,education_y,campaign_calls,contact,outcome
0,1,34,admin,single,university.degree,1500,yes,no,yes,34.0,admin,single,university.degree,2.0,cellular,yes
1,2,45,blue-collar,married,high.school,800,yes,yes,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,29,technician,single,university.degree,2100,no,no,yes,29.0,technician,single,university.degree,1.0,cellular,yes
3,4,52,services,divorced,basic.9y,300,yes,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,41,management,married,university.degree,5200,no,no,yes,41.0,management,married,university.degree,3.0,telephone,yes
5,6,38,technician,single,professional.course,1800,yes,no,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,60,retired,married,basic.4y,9800,no,no,yes,60.0,retired,married,basic.4y,1.0,cellular,yes
7,8,27,student,single,university.degree,100,no,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,48,entrepreneur,divorced,high.school,640,yes,yes,no,48.0,entrepreneur,divorced,high.school,4.0,cellular,no
9,10,35,admin,married,university.degree,2300,yes,no,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,55,housemaid,married,basic.4y,450,yes,no,no,55.0,housemaid,married,basic.4y,2.0,telephone,no
11,12,43,self-employed,single,professional.course,3100,no,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,31,unemployed,single,high.school,200,no,yes,no,31.0,unemployed,single,high.school,5.0,cellular,no
13,14,50,management,married,university.degree,7600,no,no,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,26,student,single,university.degree,80,no,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Outer Merge
Returns all rows from both A and B; fills NaN wherever data is missing.

In [5]:
df_outer = pd.merge(df_A, df_B, on='client_id', how='outer')

print('Outer merge shape:', df_outer.shape)
print('client_ids only in A:', df_outer[df_outer['outcome'].isna()]['client_id'].tolist())
print('client_ids only in B:', df_outer[df_outer['balance'].isna()]['client_id'].tolist())
display(df_outer)

Outer merge shape: (20, 16)
client_ids only in A: [2, 4, 6, 8, 10, 12, 14, 15]
client_ids only in B: [16, 17, 18, 19, 20]

,client_id,age_x,job_x,marital_x,education_x,balance,housing,loan,subscribed,age_y,job_y,marital_y,education_y,campaign_calls,contact,outcome
0,1,34.0,admin,single,university.degree,1500.0,yes,no,yes,34.0,admin,single,university.degree,2.0,cellular,yes
1,2,45.0,blue-collar,married,high.school,800.0,yes,yes,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,29.0,technician,single,university.degree,2100.0,no,no,yes,29.0,technician,single,university.degree,1.0,cellular,yes
3,4,52.0,services,divorced,basic.9y,300.0,yes,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,41.0,management,married,university.degree,5200.0,no,no,yes,41.0,management,married,university.degree,3.0,telephone,yes
5,6,38.0,technician,single,professional.course,1800.0,yes,no,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,60.0,retired,married,basic.4y,9800.0,no,no,yes,60.0,retired,married,basic.4y,1.0,cellular,yes
7,8,27.0,student,single,university.degree,100.0,no,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,48.0,entrepreneur,divorced,high.school,640.0,yes,yes,no,48.0,entrepreneur,divorced,high.school,4.0,cellular,no
9,10,35.0,admin,married,university.degree,2300.0,yes,no,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,55.0,housemaid,married,basic.4y,450.0,yes,no,no,55.0,housemaid,married,basic.4y,2.0,telephone,no
11,12,43.0,self-employed,single,professional.course,3100.0,no,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,31.0,unemployed,single,high.school,200.0,no,yes,no,31.0,unemployed,single,high.school,5.0,cellular,no
13,14,50.0,management,married,university.degree,7600.0,no,no,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,26.0,student,single,university.degree,80.0,no,no,no,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.0,admin,divorced,university.degree,2.0,cellular,yes
16,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33.0,technician,married,professional.course,1.0,cellular,yes
17,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.0,retired,married,basic.9y,1.0,cellular,yes
18,19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.0,student,single,university.degree,3.0,cellular,no
19,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.0,management,married,university.degree,2.0,telephone,yes