In [8]:
import pandas as pd

In [9]:
df = pd.read_csv('employee_salary.csv')
print("Dataset Shape:", df.shape)
print("No of rows: ",df.shape[0])
print("No of columns: ",df.shape[1])
print("\nFirst 5 Records:")
display(df.head())
print("\nLast 5 Records:")
display(df.tail())

Dataset Shape: (12, 1)
No of rows:  12
No of columns:  1

First 5 Records:

  EmployeeID\tName\tDepartment\tAge\tExperience\tSalary
0                        101\tJohn\tHR\t30\t5\t45000
1                       102\tSmith\tIT\t28\t3\t55000
2                 103\tAlice\tFinance\t35\t10\t75000
3                        104\tBob\tIT\t40\t15\t90000
4                     105\tCharlie\tHR\t25\t2\t40000

Last 5 Records:

   EmployeeID\tName\tDepartment\tAge\tExperience\tSalary
7                      108\tFrank\tIT\t45\t20\t110000
8                   109\tGrace\tFinance\t31\t6\t65000
9                    110\tHeidi\tSales\t38\t12\t85000
10                        101\tJohn\tHR\t30\t5\t45000
11                       102\tSmith\tIT\t28\t3\t55000

In [10]:
print("Column Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nMetadata:")
df.info()

print("\nDescriptive Statistics:")
display(df.describe())

Column Names:
['EmployeeID\tName\tDepartment\tAge\tExperience\tSalary']

Data Types:
EmployeeID\tName\tDepartment\tAge\tExperience\tSalary    str
dtype: object

Metadata:
<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 1 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   EmployeeID	Name	Department	Age	Experience	Salary  12 non-null     str
dtypes: str(1)
memory usage: 228.0 bytes

Descriptive Statistics:

       EmployeeID\tName\tDepartment\tAge\tExperience\tSalary
count                                                  12
unique                                                 10
top                           101\tJohn\tHR\t30\t5\t45000
freq                                                    2

In [12]:
print("Missing Values in Each Column:")
print(df.isnull().sum())

print("\nPercentage of Missing Values (%):")
print((df.isnull().sum() / len(df)) * 100)

print("Column with highest missing entries: ")
print(df.isnull().sum().idxmax())

print("Dataset Size Before Cleaning:", len(df))
print("Number of Duplicates:", df.duplicated().sum())

# Clean the dataset
df_cleaned = df.drop_duplicates()
print("Dataset Size After Cleaning:", len(df_cleaned))

Missing Values in Each Column:
EmployeeID\tName\tDepartment\tAge\tExperience\tSalary    0
dtype: int64

Percentage of Missing Values (%):
EmployeeID\tName\tDepartment\tAge\tExperience\tSalary    0.0
dtype: float64
Column with highest missing entries:
EmployeeID	Name	Department	Age	Experience	Salary
Dataset Size Before Cleaning: 12
Number of Duplicates: 2
Dataset Size After Cleaning: 10